# -*- coding: utf-8 -*-
"""M09_HelloWorld.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eHQ0g6vwfB-57NX2Cq8LmwhqZ7lkoeCF

1. Exercise 1
"""

print('Hello World')

"""2"""



"""3"""



"""4"""



"""5"""



"""6"""



"""7"""



"""8"""



"""9"""



"""10"""



"""11"""



"""12"""



"""13"""



"""14"""



"""15"""



"""16"""

