# -*- coding: utf-8 -*-
"""SetupFile.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Okjk0kzAkwlGySEIpKJi130cRrGk9u2
"""

src
    a_package_dir
        __init__.py
        module_a.py
tests
    ...