# -*- coding: utf-8 -*-
"""setup.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Okjk0kzAkwlGySEIpKJi130cRrGk9u2
"""

from setuptools import setup

setup(name='setup',
      version='0.1',
      description='Asimple demonstration package',
      url='https://github.com/ohashin2G/DS5100_Project.git',
      author='N. Ohashi',
      author_email='fju4ek@virginia.edu',
      license='MIT'
      pakcages=['deomo'])