# -*- coding: utf-8 -*-
"""SetupFile.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Okjk0kzAkwlGySEIpKJi130cRrGk9u2
"""

from setuptools import setup

setup(name='Setup',
      version=1.0
      pakcages=['deomo'])